os: linux
dist: xenial
language: python
python: "3.7"
install:
  - pip install conan protobuf
before_script:
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
script:
  - mkdir build && cd build
  - conan install ..
  - cmake ..
  - cmake --build .
  - bin/sensor
  - cd ..
  - python main.py
