#! /usr/bin/env python
# encoding: utf-8
import os

top = os.getcwd()
out = 'build'


def options(opt):
    opt.load('compiler_cxx')


def configure(conf):
    conf.load('compiler_cxx')
    conf.load('waf_conan_libs_info', tooldir=os.getcwd())
    conf.load('waf_conan_toolchain', tooldir=os.getcwd())


def build(bld):
    bld.program(source='main.cpp', target='app', use=bld.env.CONAN_LIBS)
